version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=test
          cd terragrunt
          docker build -t gruntwork/terragrunt:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push gruntwork/terragrunt:$TAG
